server:
  port: 9090
spring:
  application:
    name: JRTP-Plans-API-01
  datasource:
    driver-class-name: org.h2.Driver
    password: password
    url: jdbc:h2:mem:planDB
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
      
plan-api:
  messages:
    planSaveSucc: Plan Saved Successfully
    planSaveFail: Plan Save Failed
    planUpdateSucc: Plan Updated Successfully
    planUpdateFail: Plan Update Failed
    planDeleteSucc: Paln Deleted Successfully
    planDeleteFail: Plan Delete Failed
    planStatusChangeSucc: Plan Status Changed Successfully
    planStatusChnageFail: Plan Status Change Failed
